# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Move into client and build
WORKDIR /app/client
RUN npm install
RUN npm run build

# Production stage
FROM nginx:stable-alpine

# MATCHING YOUR VITE CONFIG: 
# Your outDir is "build", not "dist"
COPY --from=build /app/client/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]